// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wuekjqwxacvfqamvrayo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind1ZWtqcXd4YWN2ZnFhbXZyYXlvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQzOTI2NzUsImV4cCI6MjA2OTk2ODY3NX0.Sr3fFpP0bhoG3oKoMgFIMqB9kJTWOZxfN9ENmH_qN8o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});